# Generated by Django 6.0.5 on 2026-05-21 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancerMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('expected_trend', models.CharField(choices=[('decrease', 'Should decrease over time'), ('normalize', 'Should normalize to healthy range'), ('suppress', 'Should stay suppressed/low')], max_length=20)),
                ('guidance_text', models.TextField()),
                ('cancer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='biomarkers.cancertype')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('cancer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biomarkers.cancertype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_profiles', to='accounts.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BiomarkerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('reading_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biomarkers.cancermarker')),
                ('cancer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='biomarkers.patientcancerprofile')),
            ],
            options={
                'ordering': ['reading_date'],
            },
        ),
    ]
