# Generated by Django 6.0.5 on 2026-05-21 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
                ('treatment_type', models.CharField(choices=[('chemotherapy', 'Chemotherapy'), ('radiation', 'Radiation Therapy'), ('surgery', 'Surgery'), ('immunotherapy', 'Immunotherapy'), ('hormone', 'Hormone Therapy'), ('targeted', 'Targeted Therapy'), ('bone_marrow', 'Bone Marrow Transplant'), ('radioactive_iodine', 'Radioactive Iodine'), ('other', 'Other')], max_length=20)),
                ('doctor_name', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_cycles', models.IntegerField(blank=True, null=True)),
                ('cycles_completed', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile')),
            ],
        ),
    ]
